name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        run: |
          git remote add huggingface https://Ashutosh0101:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Ashutosh0101/UTM-Automation
          git push huggingface main --force
